// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReaAcademyFinalExam.Models;

namespace ReaAcademyFinalExam.Migrations
{
    [DbContext(typeof(NoteContext))]
    [Migration("20220608072949_notedatabase")]
    partial class notedatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ReaAcademyFinalExam.Models.Categories", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("categoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ReaAcademyFinalExam.Models.Notes", b =>
                {
                    b.Property<int>("noteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("categoriescategoryID")
                        .HasColumnType("int");

                    b.Property<string>("categoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noteContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tagName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tagstagID")
                        .HasColumnType("int");

                    b.HasKey("noteID");

                    b.HasIndex("categoriescategoryID");

                    b.HasIndex("tagstagID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("ReaAcademyFinalExam.Models.Tags", b =>
                {
                    b.Property<int>("tagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tagName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tagID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ReaAcademyFinalExam.Models.Notes", b =>
                {
                    b.HasOne("ReaAcademyFinalExam.Models.Categories", "categories")
                        .WithMany()
                        .HasForeignKey("categoriescategoryID");

                    b.HasOne("ReaAcademyFinalExam.Models.Tags", "tags")
                        .WithMany()
                        .HasForeignKey("tagstagID");

                    b.Navigation("categories");

                    b.Navigation("tags");
                });
#pragma warning restore 612, 618
        }
    }
}
